INSERT INTO settings VALUES ('turn_restriction_cost', '10000000', 'Cost of making a restricted turn');
INSERT INTO settings VALUES ('one_way_cost', '10000000', 'Cost of going down a one-way part of the network');
INSERT INTO settings VALUES ('car_morning_peak', '1.55', 'Increase in morning peak times for car traffic in urban areas. Source: https://www.tomtom.com/en_gb/trafficindex/city/sheffield');
INSERT INTO settings VALUES ('car_evening_peak', '1.65', 'Increase in evening peak times for car traffic in urban areas. Source: https://www.tomtom.com/en_gb/trafficindex/city/sheffield');
INSERT INTO settings VALUES ('bus_morning_peak', '1.0', 'Increase in morning peak times for bus traffic in urban areas.');
INSERT INTO settings VALUES ('bus_evening_peak', '1.0', 'Increase in evening peak times for bus traffic in urban areas.');
INSERT INTO settings VALUES ('walk_morning_peak', '1.0', 'Increase in morning peak times for walking in urban areas.');
INSERT INTO settings VALUES ('walk_evening_peak', '1.0', 'Increase in evening peak times for walking in urban areas.');
INSERT INTO settings VALUES ('cycle_morning_peak', '1.0', 'Increase in morning peak times for cycle traffic in urban areas.');
INSERT INTO settings VALUES ('cycle_evening_peak', '1.0', 'Increase in evening peak times for cycle traffic in urban areas.');
INSERT INTO settings VALUES ('met_01010', '4.0', 'bicycling, <10 mph, leisure, to work or for pleasure');
INSERT INTO settings VALUES ('met_01015', '8.7', 'bicycling, general');
INSERT INTO settings VALUES ('met_01020', '6.0', 'bicycling, 10-11.9 mph, leisure, slow, light effort');
INSERT INTO settings VALUES ('met_01030', '8.0', 'bicycling, 12-13.9 mph, leisure, moderate effort');
INSERT INTO settings VALUES ('met_01040', '10.0', 'bicycling, 14-15.9 mph, racing or leisure, fast, vigorous effort');
INSERT INTO settings VALUES ('met_01050', '10.0', 'bicycling, 16-19 mph, racing/not drafting or > 19 mph drafting, very fast, racing general');
INSERT INTO settings VALUES ('met_01060', '16.0', 'bicycling, > 20 mph, racing, not drafting');
INSERT INTO settings VALUES ('met_16015', '1.3', 'car, riding in a car or truck');
INSERT INTO settings VALUES ('met_16016', '1.3', 'bus, riding in a bus or train');
INSERT INTO settings VALUES ('met_16060', '3.5', 'walking, walking for transportation, 2.8-3.2 mph, level, moderate pace, firm surface');
INSERT INTO settings VALUES ('met_17030', '3.5', 'walking, descending stairs');
INSERT INTO settings VALUES ('met_17080', '6.0', 'walking, hiking, cross country (Taylor Code 040)');
INSERT INTO settings VALUES ('met_17082', '5.3', 'walking, hiking or walking at a normal pace through fields and hillsides');
INSERT INTO settings VALUES ('met_17085', '2.5', 'walking, bird watching, slow walk');
INSERT INTO settings VALUES ('met_17088', '4.5', 'walking, marching, moderate speed, military, no pack');
INSERT INTO settings VALUES ('met_17133', '4.0', 'walking, stair climbing, slow pace');
INSERT INTO settings VALUES ('met_17134', '8.8', 'walking, stair climbing, fast pace');
INSERT INTO settings VALUES ('met_17150', '2.0', 'walking, household');
INSERT INTO settings VALUES ('met_17151', '2.0', 'walking, less than 2.0 mph, level, strolling, very slow');
INSERT INTO settings VALUES ('met_17152', '2.8', 'walking, 2.0 mph, level, slow pace, firm surface');
INSERT INTO settings VALUES ('met_17160', '3.5', 'walking for pleasure (Taylor Code 010)');
INSERT INTO settings VALUES ('met_17161', '2.5', 'walking from house to car or bus, from car or bus to go places, from car or bus to and from the worksite');
INSERT INTO settings VALUES ('met_17170', '3.0', 'walking, 2.5 mph, level, firm surface');
INSERT INTO settings VALUES ('met_17180', '3.3', 'walking, 2.5 mph, downhill');
INSERT INTO settings VALUES ('met_17190', '3.5', 'walking, 2.8 to 3.2 mph, level, moderate pace, firm surface');
INSERT INTO settings VALUES ('met_17200', '4.3', 'walking, 3.5 mph, level, brisk, firm surface, walking for exercise');
INSERT INTO settings VALUES ('met_17210', '5.3', 'walking, 2.9 to 3.5 mph, uphill, 1 to 5% grade');
INSERT INTO settings VALUES ('met_17211', '8.0', 'walking, 2.9 to 3.5 mph, uphill, 6% to 15% grade');
INSERT INTO settings VALUES ('met_17230', '7.0', 'walking, 4.5 mph, level, firm surface, very, very brisk');
INSERT INTO settings VALUES ('met_17250', '3.5', 'walking, for pleasure, work break');
INSERT INTO settings VALUES ('met_17260', '4.8', 'walking, grass track');
INSERT INTO settings VALUES ('met_17262', '4.5', 'walking, normal pace, plowed field or sand');
INSERT INTO settings VALUES ('met_17270', '4.0', 'walking, to work or class (Taylor Code 015)');
INSERT INTO settings VALUES ('met_16010', '2.5', 'car, automobile or light truck (not a semi) driving');
INSERT INTO settings VALUES ('weight_female_average', '70.2', 'UK female average weight (kg). Average height is 161.6cm. Source: ONS Average Brition https://www.ons.gov.uk/ons/about-ons/get-involved/events/events/un-world-statictics-day/-average--briton-highlighted-on-un-world-statistics-day.pdf');
INSERT INTO settings VALUES ('weight_male_average', '83.6', 'UK male average weight (kg). Average height is 175.3cm. Source: ONS Average Brition https://www.ons.gov.uk/ons/about-ons/get-involved/events/events/un-world-statictics-day/-average--briton-highlighted-on-un-world-statistics-day.pdf');
INSERT INTO settings VALUES ('weight_female_standard_deviation', '15.911', 'Standard deviation of weight (kg). Source: http://biobank.ctsu.ox.ac.uk/crystal/field.cgi?id=21002');
INSERT INTO settings VALUES ('weight_male_standard_deviation', '15.911', 'Standard deviation of weight (kg). Source: http://biobank.ctsu.ox.ac.uk/crystal/field.cgi?id=21002');
INSERT INTO settings VALUES ('cycle_dismount_length', '50', 'Length in meters that a cyclist will dismount and walk a section of footway (or at least cycle at walking speed. This allows use of short sections of footways for cycle routing.');
INSERT INTO settings VALUES ('cycle_naismith', '8.0', 'Cycling version Naismiths rule: 1 meter of verticle ascent = Equivalent of Y meters of additional length of flat');
INSERT INTO settings VALUES ('walk_naismith', '7.92', 'Naismiths rule: 1 meter of verticle ascent = Equivalent of Y meters of additional length of flat');
INSERT INTO settings VALUES ('way_terrain_index_road', '1.0', 'The terrain index when calculating time costs associated with roads in the network');
INSERT INTO settings VALUES ('way_terrain_index_fast', '1.5', 'The terrain index when calculating time costs associated with fast quality terrain edges in the network');
INSERT INTO settings VALUES ('way_terrain_index_good', '2.0', 'The terrain index when calculating time costs associated with good quality terrain edges in the network');
INSERT INTO settings VALUES ('way_terrain_index_poor', '4.0', 'The terrain index when calculating time costs associated with poor quality terrain edges in the network');
INSERT INTO settings VALUES ('way_surface_terrain_road', 'paved; asphalt; concrete; clay; tartan; decoturf;', 'Ways with one of these surface specific attributes will be given a terrain index of "road" when calculating time costs. Semi-colon separation for multiple values.');
INSERT INTO settings VALUES ('way_surface_terrain_fast', 'concrete:lanes; concrete:plates; compacted; fine_gravel; gravel; grass_paver; artificial_turf;', 'Ways with one of these surface specific attributes will be given a terrain index of "fast" when calculating time costs. Semi-colon separation for multiple values.');
INSERT INTO settings VALUES ('way_surface_terrain_good', 'brick; paving_stones; sett; metal; wood; pebblestone; grass; gravel_turf; metal_grid;', 'Ways with one of these surface specific  attributes will be given a terrain index of "good" when calculating time costs. Semi-colon separation for multiple values.');
INSERT INTO settings VALUES ('way_surface_terrain_poor', 'unhewn_cobblestone; cobblestone; unpaved; dirt; earth; ground; mud; sand; woodchips; snow;', 'Ways with one of these surface specific  attributes will be given a terrain index of "poor" when calculating time costs. Semi-colon separation for multiple values.');
INSERT INTO settings VALUES ('way_smoothness_terrain_road', 'excellent; good;', 'Ways with one of these smoothness specific attributes will be given a terrain index of "road" when calculating time costs. Semi-colon separation for multiple values.');
INSERT INTO settings VALUES ('met_07040', '1.2', 'inactivity, quiet, standing quietly (standing in a line)');
INSERT INTO settings VALUES ('way_smoothness_terrain_fast', 'intermediate;', 'Ways with one of these smoothness specific attributes will be given a terrain index of "fast" when calculating time costs. Semi-colon separation for multiple values.');
INSERT INTO settings VALUES ('way_smoothness_terrain_good', 'bad;', 'Ways with one of these smoothness specific  attributes will be given a terrain index of "good" when calculating time costs. Semi-colon separation for multiple values.');
INSERT INTO settings VALUES ('way_smoothness_terrain_poor', 'very_bad; horrible ; very_horrible; impassable;', 'Ways with one of these smoothness specific  attributes will be given a terrain index of "poor" when calculating time costs. Semi-colon separation for multiple values.');
INSERT INTO settings VALUES ('way_tracktype_terrain_road', 'grade1;', 'Ways with one of these tracktype specific attributes will be given a terrain index of "road" when calculating time costs. Semi-colon separation for multiple values.');
INSERT INTO settings VALUES ('way_tracktype_terrain_fast', 'grade2;', 'Ways with one of these tracktype specific attributes will be given a terrain index of "fast" when calculating time costs. Semi-colon separation for multiple values.');
INSERT INTO settings VALUES ('way_tracktype_terrain_good', 'grade3;', 'Ways with one of these tracktype specific  attributes will be given a terrain index of "good" when calculating time costs. Semi-colon separation for multiple values.');
INSERT INTO settings VALUES ('way_tracktype_terrain_poor', 'grade4; grade5;', 'Ways with one of these tracktype specific  attributes will be given a terrain index of "poor" when calculating time costs. Semi-colon separation for multiple values.');
INSERT INTO settings VALUES ('walk_to_bus_dist', '500', 'Maximum distance to walk to the bus stop (in meters, as the crow flies).');
INSERT INTO settings VALUES ('walk_from_bus_dist', '750', 'Maximum distance to walk to the bus stop (in meters, as the crow flies).');
INSERT INTO settings VALUES ('walk_from_car_park', '20000', 'Maximum distance to walk from a car park to the destination (in meters, as the crow flies).');
INSERT INTO settings VALUES ('public_transport_max_cost_limit', '20000', 'Limit the cost of the public transport trip to this amount. This stops the algorithm selecting an invalid route.');
INSERT INTO settings VALUES ('public_transport_source_stop_limit', '10', 'Limit the public transport stops and routes near the journey source to this amount.');
INSERT INTO settings VALUES ('public_transport_distance_requirement', '1000', 'Required Euclidean distance between the source and target before the system checks for a public transport route');
INSERT INTO settings VALUES ('public_transport_route_direction_tolerance', '90', 'Angle in degrees which the multi modal routing uses as a tolerance to check if a route is heading towards the desired target');
INSERT INTO settings VALUES ('public_transport_direct_speed_limit', '40', 'The speed (kph) which public transport is limited to over Euclidean networks. Used to filter out multi-modal routes which have stupidly fast times.');
INSERT INTO settings VALUES ('public_transport_target_stop_limit', '10', 'Limit the public transport stops and routes near the journey target to this amount.');